//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class policy {
    
    private float versionField;
    
    private string statusCodeField;
    
    private string policyStatusDescriptionField;
    
    private string statusMessageField;
    
    private string numberField;
    
    private string nameField;
    
    private string coInsuredNameField;
    
    private string ratedStateField;
    
    private string companyField;
    
    private System.DateTime effDateField;
    
    private bool effDateFieldSpecified;
    
    private System.DateTime expDateField;
    
    private bool expDateFieldSpecified;
    
    private contact contactField;
    
    private EbillType ebillStatusField;
    
    private bool ebillStatusFieldSpecified;
    
    private EpolicyType epolicyStatusField;
    
    private bool epolicyStatusFieldSpecified;
    
    private currentPayPlan currentPayPlanField;
    
    private string recurringPaymentIndicatorField;
    
    private driver[] driversField;
    
    private vehicle[] vehiclesField;
    
    private coverage[] coveragesField;
    
    private discounts discountsField;
    
    private accidentForgivenessInfo accidentForgivenessField;
    
    private string insuranceLineCodeField;
    
    private System.Nullable<bool> pifEligibleField;
    
    private bool pifEligibleFieldSpecified;
    
    private System.Nullable<decimal> pifBalanceField;
    
    private bool pifBalanceFieldSpecified;
    
    private System.Nullable<decimal> pifDiscountField;
    
    private bool pifDiscountFieldSpecified;
    
    private System.Nullable<System.DateTime> pifPayByDateField;
    
    private bool pifPayByDateFieldSpecified;
    
    private System.DateTime physicalCancelDateField;
    
    private bool physicalCancelDateFieldSpecified;
    
    private bool lastPaymentReversedField;
    
    private bool lastPaymentReversedFieldSpecified;
    
    private bool hasMultipleRatedLocationField;
    
    private bool hasMultipleRatedLocationFieldSpecified;
    
    private string rateStructureCodeField;
    
    private billing billingField;
    
    private System.DateTime policyCancelPendingDateField;
    
    private bool policyCancelPendingDateFieldSpecified;
    
    private string policyPendingStatusField;
    
    private bool isOldNewPolicyField;
    
    private bool isOldNewPolicyFieldSpecified;
    
    private System.DateTime yearsWithCorporationDateField;
    
    private bool yearsWithCorporationDateFieldSpecified;
    
    private string policyTermField;
    
    private System.DateTime issueActivityTimeStampField;
    
    private bool issueActivityTimeStampFieldSpecified;
    
    private System.DateTime termOriginalEffectiveDateField;
    
    private bool termOriginalEffectiveDateFieldSpecified;
    
    private System.DateTime termPlannedExpirationDateField;
    
    private bool termPlannedExpirationDateFieldSpecified;
    
    private bool abridgedField;
    
    private bool abridgedFieldSpecified;
    
    /// <remarks/>
    public float version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string statusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string policyStatusDescription {
        get {
            return this.policyStatusDescriptionField;
        }
        set {
            this.policyStatusDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string statusMessage {
        get {
            return this.statusMessageField;
        }
        set {
            this.statusMessageField = value;
        }
    }
    
    /// <remarks/>
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string coInsuredName {
        get {
            return this.coInsuredNameField;
        }
        set {
            this.coInsuredNameField = value;
        }
    }
    
    /// <remarks/>
    public string ratedState {
        get {
            return this.ratedStateField;
        }
        set {
            this.ratedStateField = value;
        }
    }
    
    /// <remarks/>
    public string company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime effDate {
        get {
            return this.effDateField;
        }
        set {
            this.effDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool effDateSpecified {
        get {
            return this.effDateFieldSpecified;
        }
        set {
            this.effDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime expDate {
        get {
            return this.expDateField;
        }
        set {
            this.expDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool expDateSpecified {
        get {
            return this.expDateFieldSpecified;
        }
        set {
            this.expDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public contact contact {
        get {
            return this.contactField;
        }
        set {
            this.contactField = value;
        }
    }
    
    /// <remarks/>
    public EbillType ebillStatus {
        get {
            return this.ebillStatusField;
        }
        set {
            this.ebillStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ebillStatusSpecified {
        get {
            return this.ebillStatusFieldSpecified;
        }
        set {
            this.ebillStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public EpolicyType epolicyStatus {
        get {
            return this.epolicyStatusField;
        }
        set {
            this.epolicyStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool epolicyStatusSpecified {
        get {
            return this.epolicyStatusFieldSpecified;
        }
        set {
            this.epolicyStatusFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public currentPayPlan currentPayPlan {
        get {
            return this.currentPayPlanField;
        }
        set {
            this.currentPayPlanField = value;
        }
    }
    
    /// <remarks/>
    public string recurringPaymentIndicator {
        get {
            return this.recurringPaymentIndicatorField;
        }
        set {
            this.recurringPaymentIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("driver", IsNullable=false)]
    public driver[] drivers {
        get {
            return this.driversField;
        }
        set {
            this.driversField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("vehicle", IsNullable=false)]
    public vehicle[] vehicles {
        get {
            return this.vehiclesField;
        }
        set {
            this.vehiclesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("coverage", IsNullable=false)]
    public coverage[] coverages {
        get {
            return this.coveragesField;
        }
        set {
            this.coveragesField = value;
        }
    }
    
    /// <remarks/>
    public discounts discounts {
        get {
            return this.discountsField;
        }
        set {
            this.discountsField = value;
        }
    }
    
    /// <remarks/>
    public accidentForgivenessInfo accidentForgiveness {
        get {
            return this.accidentForgivenessField;
        }
        set {
            this.accidentForgivenessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string insuranceLineCode {
        get {
            return this.insuranceLineCodeField;
        }
        set {
            this.insuranceLineCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<bool> pifEligible {
        get {
            return this.pifEligibleField;
        }
        set {
            this.pifEligibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifEligibleSpecified {
        get {
            return this.pifEligibleFieldSpecified;
        }
        set {
            this.pifEligibleFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> pifBalance {
        get {
            return this.pifBalanceField;
        }
        set {
            this.pifBalanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifBalanceSpecified {
        get {
            return this.pifBalanceFieldSpecified;
        }
        set {
            this.pifBalanceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> pifDiscount {
        get {
            return this.pifDiscountField;
        }
        set {
            this.pifDiscountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifDiscountSpecified {
        get {
            return this.pifDiscountFieldSpecified;
        }
        set {
            this.pifDiscountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> pifPayByDate {
        get {
            return this.pifPayByDateField;
        }
        set {
            this.pifPayByDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool pifPayByDateSpecified {
        get {
            return this.pifPayByDateFieldSpecified;
        }
        set {
            this.pifPayByDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime physicalCancelDate {
        get {
            return this.physicalCancelDateField;
        }
        set {
            this.physicalCancelDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool physicalCancelDateSpecified {
        get {
            return this.physicalCancelDateFieldSpecified;
        }
        set {
            this.physicalCancelDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool lastPaymentReversed {
        get {
            return this.lastPaymentReversedField;
        }
        set {
            this.lastPaymentReversedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lastPaymentReversedSpecified {
        get {
            return this.lastPaymentReversedFieldSpecified;
        }
        set {
            this.lastPaymentReversedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public bool hasMultipleRatedLocation {
        get {
            return this.hasMultipleRatedLocationField;
        }
        set {
            this.hasMultipleRatedLocationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool hasMultipleRatedLocationSpecified {
        get {
            return this.hasMultipleRatedLocationFieldSpecified;
        }
        set {
            this.hasMultipleRatedLocationFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string rateStructureCode {
        get {
            return this.rateStructureCodeField;
        }
        set {
            this.rateStructureCodeField = value;
        }
    }
    
    /// <remarks/>
    public billing billing {
        get {
            return this.billingField;
        }
        set {
            this.billingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime policyCancelPendingDate {
        get {
            return this.policyCancelPendingDateField;
        }
        set {
            this.policyCancelPendingDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool policyCancelPendingDateSpecified {
        get {
            return this.policyCancelPendingDateFieldSpecified;
        }
        set {
            this.policyCancelPendingDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string policyPendingStatus {
        get {
            return this.policyPendingStatusField;
        }
        set {
            this.policyPendingStatusField = value;
        }
    }
    
    /// <remarks/>
    public bool isOldNewPolicy {
        get {
            return this.isOldNewPolicyField;
        }
        set {
            this.isOldNewPolicyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isOldNewPolicySpecified {
        get {
            return this.isOldNewPolicyFieldSpecified;
        }
        set {
            this.isOldNewPolicyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime yearsWithCorporationDate {
        get {
            return this.yearsWithCorporationDateField;
        }
        set {
            this.yearsWithCorporationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool yearsWithCorporationDateSpecified {
        get {
            return this.yearsWithCorporationDateFieldSpecified;
        }
        set {
            this.yearsWithCorporationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string policyTerm {
        get {
            return this.policyTermField;
        }
        set {
            this.policyTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime issueActivityTimeStamp {
        get {
            return this.issueActivityTimeStampField;
        }
        set {
            this.issueActivityTimeStampField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool issueActivityTimeStampSpecified {
        get {
            return this.issueActivityTimeStampFieldSpecified;
        }
        set {
            this.issueActivityTimeStampFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime termOriginalEffectiveDate {
        get {
            return this.termOriginalEffectiveDateField;
        }
        set {
            this.termOriginalEffectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool termOriginalEffectiveDateSpecified {
        get {
            return this.termOriginalEffectiveDateFieldSpecified;
        }
        set {
            this.termOriginalEffectiveDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime termPlannedExpirationDate {
        get {
            return this.termPlannedExpirationDateField;
        }
        set {
            this.termPlannedExpirationDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool termPlannedExpirationDateSpecified {
        get {
            return this.termPlannedExpirationDateFieldSpecified;
        }
        set {
            this.termPlannedExpirationDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool abridged {
        get {
            return this.abridgedField;
        }
        set {
            this.abridgedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool abridgedSpecified {
        get {
            return this.abridgedFieldSpecified;
        }
        set {
            this.abridgedFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class contact {
    
    private phones phonesField;
    
    private string emailField;
    
    private emailPrefs emailPrefsField;
    
    private mailing mailingField;
    
    /// <remarks/>
    public phones phones {
        get {
            return this.phonesField;
        }
        set {
            this.phonesField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public emailPrefs emailPrefs {
        get {
            return this.emailPrefsField;
        }
        set {
            this.emailPrefsField = value;
        }
    }
    
    /// <remarks/>
    public mailing mailing {
        get {
            return this.mailingField;
        }
        set {
            this.mailingField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class phones {
    
    private string homeField;
    
    private string workField;
    
    private string cellField;
    
    /// <remarks/>
    public string home {
        get {
            return this.homeField;
        }
        set {
            this.homeField = value;
        }
    }
    
    /// <remarks/>
    public string work {
        get {
            return this.workField;
        }
        set {
            this.workField = value;
        }
    }
    
    /// <remarks/>
    public string cell {
        get {
            return this.cellField;
        }
        set {
            this.cellField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class discountInfo {
    
    private string nameField;
    
    private decimal amountField;
    
    private string detailsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public decimal amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class emailPrefs {
    
    private YNType contestsPrefField;
    
    private YNType newsletterPrefField;
    
    private YNType policyPrefField;
    
    private YNType productPrefField;
    
    private YNType servicePrefField;
    
    /// <remarks/>
    public YNType contestsPref {
        get {
            return this.contestsPrefField;
        }
        set {
            this.contestsPrefField = value;
        }
    }
    
    /// <remarks/>
    public YNType newsletterPref {
        get {
            return this.newsletterPrefField;
        }
        set {
            this.newsletterPrefField = value;
        }
    }
    
    /// <remarks/>
    public YNType policyPref {
        get {
            return this.policyPrefField;
        }
        set {
            this.policyPrefField = value;
        }
    }
    
    /// <remarks/>
    public YNType productPref {
        get {
            return this.productPrefField;
        }
        set {
            this.productPrefField = value;
        }
    }
    
    /// <remarks/>
    public YNType servicePref {
        get {
            return this.servicePrefField;
        }
        set {
            this.servicePrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlRootAttribute("contestsPref", Namespace="", IsNullable=false)]
public enum YNType {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class mailing {
    
    private string address1Field;
    
    private string address2Field;
    
    private string address3Field;
    
    private string cityField;
    
    private string stateField;
    
    private string zipField;
    
    /// <remarks/>
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public string address3 {
        get {
            return this.address3Field;
        }
        set {
            this.address3Field = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlRootAttribute("ebillStatus", Namespace="", IsNullable=false)]
public enum EbillType {
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    U,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlRootAttribute("epolicyStatus", Namespace="", IsNullable=false)]
public enum EpolicyType {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute(" ")]
    Item,
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    E,
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    U,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class currentPayPlan {
    
    private string nameField;
    
    private installment[] remainingInstallmentsField;
    
    private bool specialPayPlanIndField;
    
    private bool specialPayPlanIndFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("installment", IsNullable=false)]
    public installment[] remainingInstallments {
        get {
            return this.remainingInstallmentsField;
        }
        set {
            this.remainingInstallmentsField = value;
        }
    }
    
    /// <remarks/>
    public bool specialPayPlanInd {
        get {
            return this.specialPayPlanIndField;
        }
        set {
            this.specialPayPlanIndField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool specialPayPlanIndSpecified {
        get {
            return this.specialPayPlanIndFieldSpecified;
        }
        set {
            this.specialPayPlanIndFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class installment {
    
    private System.Nullable<System.DateTime> dateField;
    
    private System.Nullable<decimal> amountField;
    
    private System.Nullable<decimal> feeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> fee {
        get {
            return this.feeField;
        }
        set {
            this.feeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class driver {
    
    private string nameField;
    
    private string firstNameField;
    
    private string lastNameField;
    
    private string middleNameField;
    
    private string suffixField;
    
    private string unitNumberField;
    
    private System.DateTime dobField;
    
    private string statusField;
    
    private gender genderField;
    
    private string licenseStateField;
    
    private string licenseNoField;
    
    private string licenseStatusField;
    
    private YNType namedInsuredField;
    
    private string relationshipToInsuredField;
    
    private bool coInsuredField;
    
    private System.DateTime driverStatusDateField;
    
    private string ownRentCodeField;
    
    private string sSNField;
    
    private bool ssnRefusedIndicatorField;
    
    private bool fullTimeStudentField;
    
    private string educationCodeField;
    
    private string educationDescriptionField;
    
    private string occupationCodeField;
    
    private string occupationDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string firstName {
        get {
            return this.firstNameField;
        }
        set {
            this.firstNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string lastName {
        get {
            return this.lastNameField;
        }
        set {
            this.lastNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string middleName {
        get {
            return this.middleNameField;
        }
        set {
            this.middleNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string suffix {
        get {
            return this.suffixField;
        }
        set {
            this.suffixField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string unitNumber {
        get {
            return this.unitNumberField;
        }
        set {
            this.unitNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime dob {
        get {
            return this.dobField;
        }
        set {
            this.dobField = value;
        }
    }
    
    /// <remarks/>
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public gender gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public string licenseState {
        get {
            return this.licenseStateField;
        }
        set {
            this.licenseStateField = value;
        }
    }
    
    /// <remarks/>
    public string licenseNo {
        get {
            return this.licenseNoField;
        }
        set {
            this.licenseNoField = value;
        }
    }
    
    /// <remarks/>
    public string licenseStatus {
        get {
            return this.licenseStatusField;
        }
        set {
            this.licenseStatusField = value;
        }
    }
    
    /// <remarks/>
    public YNType namedInsured {
        get {
            return this.namedInsuredField;
        }
        set {
            this.namedInsuredField = value;
        }
    }
    
    /// <remarks/>
    public string relationshipToInsured {
        get {
            return this.relationshipToInsuredField;
        }
        set {
            this.relationshipToInsuredField = value;
        }
    }
    
    /// <remarks/>
    public bool coInsured {
        get {
            return this.coInsuredField;
        }
        set {
            this.coInsuredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime driverStatusDate {
        get {
            return this.driverStatusDateField;
        }
        set {
            this.driverStatusDateField = value;
        }
    }
    
    /// <remarks/>
    public string ownRentCode {
        get {
            return this.ownRentCodeField;
        }
        set {
            this.ownRentCodeField = value;
        }
    }
    
    /// <remarks/>
    public string SSN {
        get {
            return this.sSNField;
        }
        set {
            this.sSNField = value;
        }
    }
    
    /// <remarks/>
    public bool ssnRefusedIndicator {
        get {
            return this.ssnRefusedIndicatorField;
        }
        set {
            this.ssnRefusedIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public bool fullTimeStudent {
        get {
            return this.fullTimeStudentField;
        }
        set {
            this.fullTimeStudentField = value;
        }
    }
    
    /// <remarks/>
    public string educationCode {
        get {
            return this.educationCodeField;
        }
        set {
            this.educationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string educationDescription {
        get {
            return this.educationDescriptionField;
        }
        set {
            this.educationDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string occupationCode {
        get {
            return this.occupationCodeField;
        }
        set {
            this.occupationCodeField = value;
        }
    }
    
    /// <remarks/>
    public string occupationDescription {
        get {
            return this.occupationDescriptionField;
        }
        set {
            this.occupationDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public enum gender {
    
    /// <remarks/>
    M,
    
    /// <remarks/>
    F,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class vehicle {
    
    private string yearField;
    
    private string makeField;
    
    private string makeFullNameField;
    
    private string modelField;
    
    private string modelFullNameField;
    
    private string unitNumberField;
    
    private string vinField;
    
    private string registeredStateField;
    
    private financeCo[] financeCosField;
    
    private coverage[] coveragesField;
    
    private discounts discountsField;
    
    private string physicalVehicleTypeCodeField;
    
    private string ratedVehicleTypeCodeField;
    
    private string driverOwnerNumber1Field;
    
    private string driverOwnerNumber2Field;
    
    private bool hasERSCoverageField;
    
    private bool hasRentalCoverageField;
    
    private string daysDrivenToSchoolField;
    
    private string daysDrivenToWorkField;
    
    private string milesDrivenToSchoolField;
    
    private string milesDrivenToWorkField;
    
    private string primaryDriverField;
    
    private string principalUseField;
    
    private @operator[] operatorsField;
    
    private System.DateTime effectiveDateField;
    
    private System.DateTime purchaseDateField;
    
    private string locationZipField;
    
    private garagedLocation garagedLocationField;
    
    private bool businessOwnedIndicatorField;
    
    private string relationTypeCodeField;
    
    private businessOwnerDetails businessOwnerDetailsField;
    
    private string replacementVehicleIndicatorField;
    
    private bool historicalVehicleIndicatorField;
    
    private System.DateTime originalEffectiveDateField;
    
    private string antiTheftDeviceCodeField;
    
    private string antiThetfDeviceDescriptionField;
    
    private string passiveRestraintDeviceCodeField;
    
    private string passiveRestraintDeviceDescriptionField;
    
    private bool daytimeRunningLightsField;
    
    private bool antiLockBrakesField;
    
    private bool hybridIndicatorField;
    
    private string vehicleTypeDescriptionField;
    
    private bool customizationsField;
    
    private string inspectionStatusCodeField;
    
    private string inspectionStatusDescriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public string make {
        get {
            return this.makeField;
        }
        set {
            this.makeField = value;
        }
    }
    
    /// <remarks/>
    public string makeFullName {
        get {
            return this.makeFullNameField;
        }
        set {
            this.makeFullNameField = value;
        }
    }
    
    /// <remarks/>
    public string model {
        get {
            return this.modelField;
        }
        set {
            this.modelField = value;
        }
    }
    
    /// <remarks/>
    public string modelFullName {
        get {
            return this.modelFullNameField;
        }
        set {
            this.modelFullNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string unitNumber {
        get {
            return this.unitNumberField;
        }
        set {
            this.unitNumberField = value;
        }
    }
    
    /// <remarks/>
    public string vin {
        get {
            return this.vinField;
        }
        set {
            this.vinField = value;
        }
    }
    
    /// <remarks/>
    public string registeredState {
        get {
            return this.registeredStateField;
        }
        set {
            this.registeredStateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("financeCo", IsNullable=false)]
    public financeCo[] financeCos {
        get {
            return this.financeCosField;
        }
        set {
            this.financeCosField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("coverage", IsNullable=false)]
    public coverage[] coverages {
        get {
            return this.coveragesField;
        }
        set {
            this.coveragesField = value;
        }
    }
    
    /// <remarks/>
    public discounts discounts {
        get {
            return this.discountsField;
        }
        set {
            this.discountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string physicalVehicleTypeCode {
        get {
            return this.physicalVehicleTypeCodeField;
        }
        set {
            this.physicalVehicleTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ratedVehicleTypeCode {
        get {
            return this.ratedVehicleTypeCodeField;
        }
        set {
            this.ratedVehicleTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string driverOwnerNumber1 {
        get {
            return this.driverOwnerNumber1Field;
        }
        set {
            this.driverOwnerNumber1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer", IsNullable=true)]
    public string driverOwnerNumber2 {
        get {
            return this.driverOwnerNumber2Field;
        }
        set {
            this.driverOwnerNumber2Field = value;
        }
    }
    
    /// <remarks/>
    public bool hasERSCoverage {
        get {
            return this.hasERSCoverageField;
        }
        set {
            this.hasERSCoverageField = value;
        }
    }
    
    /// <remarks/>
    public bool hasRentalCoverage {
        get {
            return this.hasRentalCoverageField;
        }
        set {
            this.hasRentalCoverageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string daysDrivenToSchool {
        get {
            return this.daysDrivenToSchoolField;
        }
        set {
            this.daysDrivenToSchoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string daysDrivenToWork {
        get {
            return this.daysDrivenToWorkField;
        }
        set {
            this.daysDrivenToWorkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string milesDrivenToSchool {
        get {
            return this.milesDrivenToSchoolField;
        }
        set {
            this.milesDrivenToSchoolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string milesDrivenToWork {
        get {
            return this.milesDrivenToWorkField;
        }
        set {
            this.milesDrivenToWorkField = value;
        }
    }
    
    /// <remarks/>
    public string primaryDriver {
        get {
            return this.primaryDriverField;
        }
        set {
            this.primaryDriverField = value;
        }
    }
    
    /// <remarks/>
    public string principalUse {
        get {
            return this.principalUseField;
        }
        set {
            this.principalUseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("operator", IsNullable=false)]
    public @operator[] operators {
        get {
            return this.operatorsField;
        }
        set {
            this.operatorsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime effectiveDate {
        get {
            return this.effectiveDateField;
        }
        set {
            this.effectiveDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime purchaseDate {
        get {
            return this.purchaseDateField;
        }
        set {
            this.purchaseDateField = value;
        }
    }
    
    /// <remarks/>
    public string locationZip {
        get {
            return this.locationZipField;
        }
        set {
            this.locationZipField = value;
        }
    }
    
    /// <remarks/>
    public garagedLocation garagedLocation {
        get {
            return this.garagedLocationField;
        }
        set {
            this.garagedLocationField = value;
        }
    }
    
    /// <remarks/>
    public bool businessOwnedIndicator {
        get {
            return this.businessOwnedIndicatorField;
        }
        set {
            this.businessOwnedIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string relationTypeCode {
        get {
            return this.relationTypeCodeField;
        }
        set {
            this.relationTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    public businessOwnerDetails businessOwnerDetails {
        get {
            return this.businessOwnerDetailsField;
        }
        set {
            this.businessOwnerDetailsField = value;
        }
    }
    
    /// <remarks/>
    public string replacementVehicleIndicator {
        get {
            return this.replacementVehicleIndicatorField;
        }
        set {
            this.replacementVehicleIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public bool historicalVehicleIndicator {
        get {
            return this.historicalVehicleIndicatorField;
        }
        set {
            this.historicalVehicleIndicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime originalEffectiveDate {
        get {
            return this.originalEffectiveDateField;
        }
        set {
            this.originalEffectiveDateField = value;
        }
    }
    
    /// <remarks/>
    public string antiTheftDeviceCode {
        get {
            return this.antiTheftDeviceCodeField;
        }
        set {
            this.antiTheftDeviceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string antiThetfDeviceDescription {
        get {
            return this.antiThetfDeviceDescriptionField;
        }
        set {
            this.antiThetfDeviceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string passiveRestraintDeviceCode {
        get {
            return this.passiveRestraintDeviceCodeField;
        }
        set {
            this.passiveRestraintDeviceCodeField = value;
        }
    }
    
    /// <remarks/>
    public string passiveRestraintDeviceDescription {
        get {
            return this.passiveRestraintDeviceDescriptionField;
        }
        set {
            this.passiveRestraintDeviceDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public bool daytimeRunningLights {
        get {
            return this.daytimeRunningLightsField;
        }
        set {
            this.daytimeRunningLightsField = value;
        }
    }
    
    /// <remarks/>
    public bool antiLockBrakes {
        get {
            return this.antiLockBrakesField;
        }
        set {
            this.antiLockBrakesField = value;
        }
    }
    
    /// <remarks/>
    public bool hybridIndicator {
        get {
            return this.hybridIndicatorField;
        }
        set {
            this.hybridIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string vehicleTypeDescription {
        get {
            return this.vehicleTypeDescriptionField;
        }
        set {
            this.vehicleTypeDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public bool customizations {
        get {
            return this.customizationsField;
        }
        set {
            this.customizationsField = value;
        }
    }
    
    /// <remarks/>
    public string inspectionStatusCode {
        get {
            return this.inspectionStatusCodeField;
        }
        set {
            this.inspectionStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string inspectionStatusDescription {
        get {
            return this.inspectionStatusDescriptionField;
        }
        set {
            this.inspectionStatusDescriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class financeCo {
    
    private string nameField;
    
    private string address1Field;
    
    private string address2Field;
    
    private string address3Field;
    
    private string financeTypeField;
    
    private string clientIdField;
    
    private string relationTypeCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public string address3 {
        get {
            return this.address3Field;
        }
        set {
            this.address3Field = value;
        }
    }
    
    /// <remarks/>
    public string financeType {
        get {
            return this.financeTypeField;
        }
        set {
            this.financeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string clientId {
        get {
            return this.clientIdField;
        }
        set {
            this.clientIdField = value;
        }
    }
    
    /// <remarks/>
    public string relationTypeCode {
        get {
            return this.relationTypeCodeField;
        }
        set {
            this.relationTypeCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class coverage {
    
    private string nameField;
    
    private string limitDedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string limitDed {
        get {
            return this.limitDedField;
        }
        set {
            this.limitDedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class discounts {
    
    private discountInfo[] appliedDiscountsField;
    
    private discountInfo[] additionalDiscountsField;
    
    private decimal totalPremiumBeforeDiscountsField;
    
    private decimal totalPremiumAfterDiscountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("appliedDiscounts")]
    public discountInfo[] appliedDiscounts {
        get {
            return this.appliedDiscountsField;
        }
        set {
            this.appliedDiscountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("additionalDiscounts")]
    public discountInfo[] additionalDiscounts {
        get {
            return this.additionalDiscountsField;
        }
        set {
            this.additionalDiscountsField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalPremiumBeforeDiscounts {
        get {
            return this.totalPremiumBeforeDiscountsField;
        }
        set {
            this.totalPremiumBeforeDiscountsField = value;
        }
    }
    
    /// <remarks/>
    public decimal totalPremiumAfterDiscounts {
        get {
            return this.totalPremiumAfterDiscountsField;
        }
        set {
            this.totalPremiumAfterDiscountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class @operator {
    
    private string driverNumberField;
    
    private bool mostUsedIndicatorField;
    
    private string operatorTypeCodeField;
    
    private string vehicleUnitNumberField;
    
    private string vehicleUsagePercentageField;
    
    /// <remarks/>
    public string driverNumber {
        get {
            return this.driverNumberField;
        }
        set {
            this.driverNumberField = value;
        }
    }
    
    /// <remarks/>
    public bool mostUsedIndicator {
        get {
            return this.mostUsedIndicatorField;
        }
        set {
            this.mostUsedIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string operatorTypeCode {
        get {
            return this.operatorTypeCodeField;
        }
        set {
            this.operatorTypeCodeField = value;
        }
    }
    
    /// <remarks/>
    public string vehicleUnitNumber {
        get {
            return this.vehicleUnitNumberField;
        }
        set {
            this.vehicleUnitNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string vehicleUsagePercentage {
        get {
            return this.vehicleUsagePercentageField;
        }
        set {
            this.vehicleUsagePercentageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class garagedLocation {
    
    private string streetField;
    
    private string cityField;
    
    private string stateField;
    
    private string zipField;
    
    /// <remarks/>
    public string street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public string zip {
        get {
            return this.zipField;
        }
        set {
            this.zipField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class businessOwnerDetails {
    
    private string businessNameField;
    
    private string federalEmployeeIdentificationNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string businessName {
        get {
            return this.businessNameField;
        }
        set {
            this.businessNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string federalEmployeeIdentificationNumber {
        get {
            return this.federalEmployeeIdentificationNumberField;
        }
        set {
            this.federalEmployeeIdentificationNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute("accidentForgiveness", Namespace="", IsNullable=false)]
public partial class accidentForgivenessInfo {
    
    private string uafEligibleField;
    
    private string uafPurchasedField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string uafEligible {
        get {
            return this.uafEligibleField;
        }
        set {
            this.uafEligibleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string uafPurchased {
        get {
            return this.uafPurchasedField;
        }
        set {
            this.uafPurchasedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class billing {
    
    private string paymentRestrictionIndicatorField;
    
    private string payPlanCodeField;
    
    private string payPlanDescriptionField;
    
    private string specialPayPlanIndicatorField;
    
    /// <remarks/>
    public string paymentRestrictionIndicator {
        get {
            return this.paymentRestrictionIndicatorField;
        }
        set {
            this.paymentRestrictionIndicatorField = value;
        }
    }
    
    /// <remarks/>
    public string payPlanCode {
        get {
            return this.payPlanCodeField;
        }
        set {
            this.payPlanCodeField = value;
        }
    }
    
    /// <remarks/>
    public string payPlanDescription {
        get {
            return this.payPlanDescriptionField;
        }
        set {
            this.payPlanDescriptionField = value;
        }
    }
    
    /// <remarks/>
    public string specialPayPlanIndicator {
        get {
            return this.specialPayPlanIndicatorField;
        }
        set {
            this.specialPayPlanIndicatorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class remainingInstallments {
    
    private installment[] installmentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("installment")]
    public installment[] installment {
        get {
            return this.installmentField;
        }
        set {
            this.installmentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class drivers {
    
    private driver[] driverField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("driver")]
    public driver[] driver {
        get {
            return this.driverField;
        }
        set {
            this.driverField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class vehicles {
    
    private vehicle[] vehicleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("vehicle")]
    public vehicle[] vehicle {
        get {
            return this.vehicleField;
        }
        set {
            this.vehicleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class financeCos {
    
    private financeCo[] financeCoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("financeCo")]
    public financeCo[] financeCo {
        get {
            return this.financeCoField;
        }
        set {
            this.financeCoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class coverages {
    
    private coverage[] coverageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("coverage")]
    public coverage[] coverage {
        get {
            return this.coverageField;
        }
        set {
            this.coverageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class operators {
    
    private @operator[] operatorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("operator")]
    public @operator[] @operator {
        get {
            return this.operatorField;
        }
        set {
            this.operatorField = value;
        }
    }
}
